# Generated by Django 4.2.3 on 2023-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callebautuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
